name: Deploy Zeile Document

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1
      - name: Install Package
        run: npm ci --ignore-scripts=false
      - name: Build
        run: npm run docs:build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: src/.vuepress/dist/
          retention-days: 30
      - name: Deploy Pages
        uses: actions/deploy-pages@v4.0.5
        
